parameters:
  name: ''  # defaults for any parameters that aren't specified
  displayName: ''
  vmImage: ''
  OS: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:    
      vmImage: ${{ parameters.vmImage }}

    dependsOn: ${{ parameters.dependsOn }}

    continueOnError: false
    
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 2

    variables:
      OS: ${{ parameters.OS }}

    steps:
    - template: templates/conda_config.yml

    - bash:  conda install -y -q conda-build=3
      displayName: Installing conda-build

    - ${{ if eq(parameters.OS, 'linux') }}:  # Don't build pypi for OSX. It's platform independent
      - template: templates/build_pypi_artifact.yml
      
    - template: templates/build_conda_artifact.yml

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: htmd_$(OS)_$(python.version)