parameters:
  name: ''  # defaults for any parameters that aren't specified
  displayName: ''
  vmImage: ''
  OS: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:    
      vmImage: ${{ parameters.vmImage }}

    continueOnError: false
    
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 2

    variables:
      OS: ${{ parameters.OS }}

    steps:
    - template: templates/conda_config.yml
    - template: templates/run_tests.yml