#!/usr/bin/env bash

. ../routines

for IN in $(find . -name "*.gjf"); do
	OUT=$(echo "$IN" | sed 's/.gjf$/.out/g' )
	if [ ! -e "$OUT" ]; then
		echo "Running $IN"
		CHECK $BIN_G09 $IN $OUT
	else
		echo "Skipping $N"
	fi
done
