#!/bin/bash

source ../routines

if [ -e ligand.pdb ]; then
	# to stop false debug error
	CHECK $BIN_BABEL -i pdb ligand.pdb -o mol2 ligand.mol2
fi

CHECK $BIN_BABEL -i mol2 ligand.mol2 ligand.xyz

exit 0
