#!/bin/bash
#source $GAAMPSCRIPTS/routines
source ../routines

if [ "$1" == "" ]; then
	CHECK $BIN_DON_ACC_SEPARATE  --prepare
	CHECK $BIN_ACCEPTOR --prepare
	CHECK $BIN_DONOR    --prepare
	CHECK $BIN_RUN_QM_JOBS
	CHECK $BIN_DON_ACC_SEPARATE --complete
	CHECK $BIN_ACCEPTOR --complete
	CHECK $BIN_DONOR --complete
  # Fall through to finish off the processing
elif [ "$1" == "--prepare" ]; then
	CHECK $BIN_DON_ACC_SEPARATE  --prepare
	CHECK $BIN_ACCEPTOR --prepare
	CHECK $BIN_DONOR    --prepare
  # Terminate to let calling program do the QM
	exit 0
elif [ "$1" == "--complete" ]; then
	CHECK $BIN_DON_ACC_SEPARATE --complete
	CHECK $BIN_ACCEPTOR --complete
	CHECK $BIN_DONOR --complete
  # Fall through to finish off the processing
fi

CHECK $BIN_EXTRACT_QM_MOL_WATER


if [ -e ./E-mol-wat.txt ]; then

#  $CHECK $BIN_GEN_SOFT_LIST

  NumTorsion=`wc -l soft-dih-list.txt | awk '{print $1}'`

  echo "Target_E_Int_Water" >> fit-mol.conf
  echo "FILE_MolWater_PSF   mol-wat.xpsf" >> fit-mol.conf
  echo "FILE_MolWaterEnergy E-mol-wat.txt" >> fit-mol.conf
  echo "SCALE_QM_E_MIN          1.16" >> fit-mol.conf
  echo "SHIFT_QM_R_MIN         -0.20" >> fit-mol.conf
  echo "SHIFT_QM_R_MIN_CHARGED -0.20" >> fit-mol.conf

  if [ "$NumTorsion" -eq 0 ]; then
    CHECK $BIN_FITCHARGE_AGAIN fit-mol.conf 
  else
    CHECK $BIN_FITCHARGE fit-mol.conf 
  fi

else
    touch E-mol-wat.txt
    CHECK $BIN_FITCHARGE fit-mol.conf 
fi
CHECK $BIN_UPDATE_XPSF

