#!/bin/sh
source ../routines

NumTorsion=`wc -l soft-dih-list.txt | awk '{print $1}'`

#if [ "$NumTorsion" -lt "$MaxTorsion" ]; then
  CHECK $BIN_MM_PES #Gexe mm_pes
#else
#  CHECK $BIN_MM_PES_LARGE # Gexe mm_pes_large
#fi

cat mm-pes-id-*.dat > E-phi-mm-pes.txt

CHECK $BIN_CLUSTERING_PHI


#rm opt-*.pdb

exit 0
