#!/bin/bash
source ../routines 

declare -i NumRotamer
NumRotamer=`cat n_rotamer.txt`

echo "Number of rotamers: $NumRotamer" 

VAL=0.5
BIN=$BIN_QM_ROTAMER_SCAN_LARGE

if [ "$NumRotamer" -lt 64 ]; then
	VAL=0.1
  BIN=$BIN_QM_ROTAMER_SCAN
fi

if [ "$1" == "--prepare" ]; then
	CHECK $BIN $VAL --prepare
elif [ "$1" == "--complete" ]; then
	CHECK $BIN $VAL --complete
else
	CHECK $BIN $VAL --prepare
	$BIN_RUN_QM_JOBS 
	CHECK $BIN $VAL --complete
fi

if [ ! -e QM-min.xyz ]; then
	ln -s mol-opt.xyz QM-min.xyz
fi
exit 0

