package:
  name: htmd-data
  version: "0.0.32"

source:
   path: ../..

requirements:
   build:
    - python  >=3.4

   run:
    - python >=3.4
   



about:
  home: http://www.htmd.org
  license: "Acellera Academic License version 1.1"
  license_file: htmd/ACADEMIC_LICENCE.txt
