package:
  name: htmd-data
  version: "0.0.38"

source:
   path: ../..

build:
 number: 0

requirements:
   build:
    noarch_python: True

   run:


about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
