package:
  name: htmd-data
  version: {{ environ.get('HTMD_DATA_VERSION') }}

source:
  path: ../../htmd/data/

# https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages
build:
  number: 0
  noarch: python

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: ../../htmd/data/HTMD_LICENCE.txt
