package:
  name: htmd-data
  version: "0.0.42"

source:
   path: ../..

build:
 number: 0
# noarch_python: True

requirements:
   build:
   - python

   run:
   - python

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
