package:
  name: htmd-data
  version: "0.0.37"

source:
   path: ../..

build:
 number: 0

requirements:
   build:
   - python

   run:
    - python  


about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
