package:
  name: htmd-data
  version: "0.0.33"

source:
   path: ../..

requirements:
   build:

   run:
    - python  


about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
