package:
  name: htmd-data
  version: "0.0.47"

source:
   path: ../../htmd/data/

# https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages
build:
 number: 0
 noarch: python

requirements:
   build:
   - python

   run:
   - python

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: ../../HTMD_LICENCE.txt
