import xlrd
import time

wb=xlrd.open_workbook("atomNames.xlsx")
sh=wb.sheet_by_index(0)

head = [h.value for h in sh.row(0)]


src_idx=head.index("BMRB")
dest_idx=head.index("PSFGEN")
resname_idx=head.index("AA3")

print("# Generated by gen_psfaliases.py (Toni) on "+time.strftime("%Y-%m-%d %H:%M"))
for i in range(1,sh.nrows):
    row=sh.row(i)
    an=row[src_idx].value
    cn=row[dest_idx].value
    resname=row[resname_idx].value
    resnameU=resname.upper()

    if an and cn and an != cn and  resnameU:
        print("pdbalias atom %s %s %s" % (resnameU, an, cn))

