
package:
  name: htmd-deps
  version: {{ environ.get('BUILD_VERSION') }}

source:
   path: .

requirements:
  build:
    - python
    - requests


  run:

    - pyemma 2.2.7
    - natsort 5.0.1
    - joblib 0.9.3
    - requests 2.12.4
    - scikit-learn 0.18.1
    - ipython 5.1.0
    - jupyter_console 5.0.0
    - propka 3.1.6
    - notebook 4.3.0
    - ipywidgets 5.2.2
    - ipyparallel 5.2.0
    - anaconda-client 1.6.0
    - nglview 0.6.2.1
    - vina 1.1.101
    - psfgen 1.6.9
    - pandas 0.19.1
    - pint 0.7.2
    - htmd-pdb2pqr 2.1.2a9
    - spyder 3.0.2
    - psi4 1.0.54
    - acemd 2016.10.27
    - match 0.0.2
    - ambermini 16.16.0
    - matplotlib 1.5.3
    - openbabel 2015.09
    - openpyxl 2.4.0
    - acecloud-client 1.0.34
    - pcmsolver 1.1.4
    - dftd3 3.2.0
    - pyparsing 2.1.4
    - progress_reporter 1.2
