package:
  name: {{ environ.get('PACKAGE_NAME') }}
  version: {{ environ.get('MINOR_VERSION') }}

source:
   path: ../..

build:
  number: {{ environ.get('BUGFIX', 0 ) }}

requirements:
  run:
    - htmd {{ environ.get('BUGFIX_VERSION' ) }}

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"