package:
  name: htmd
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

  script_env:
   - OSNAME

  entry_points:
    - htmd_register   = htmd.license:htmd_register

requirements:
  build:
    - python 
    - requests
    

  run:
    - python 
    - htmd-deps =={{ environ.get('BUILD_VERSION') }}

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
