package:
  name: htmd
  version: {{ environ.get('BUILD_VERSION') }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  script_env:
   - TYPE
   - FC
   - CC

  entry_points:
    - htmdnb    = htmdx.cli:main_htmd_notebook
    - htmd      = htmdx.cli:main_htmd
    - parameterize = htmd.parameterize.cli:main_parameterize
    - sample    = htmd.parameterize.sample:sample_main
    - activate_license  = htmdx.cli:main_activate

requirements:
  build:
    - python 
    - requests
    

  run:
    - python 
    - pyemma >=2.1
    - natsort
    - joblib
    - requests
    - scikit-learn
    - ipython
    - jupyter_console
    - propka
    - notebook
    - ipywidgets
    - ipyparallel
    - htmd-data >=0.0.20
    - anaconda-client
    - nglview
    - vina
    - psfgen
    
test:
  commands:
    - htmd --help
about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
