package:
  name: {{ environ.get('PACKAGE_NAME', htmd) }}
  version: {{ environ.get('BUILD_VERSION') }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  script_env:
   - TYPE
   - FC
   - CC
   - CROSS_COMPILE
   - STATIC
   - CPURE
   - OSNAME
   - TYPE

  entry_points:
    - htmdnb    = htmdx.cli:main_htmd_notebook
    - htmd      = htmdx.cli:main_htmd
    - parameterize    = htmd.parameterization.cli:main_parameterize
    - newparameterize = htmd.newparameterization.cli:main_parameterize
    - sample    = htmd.parameterization.sample:sample_main
    - activate_license  = htmdx.cli:main_activate

requirements:
  build:
    - python 
    - requests
    

  run:
    - python 
    - pyemma >=2.1
    - natsort
    - joblib
    - requests
    - scikit-learn
    - ipython
    - jupyter_console
    - propka >=3.1.6
    - notebook
    - ipywidgets
    - ipyparallel
    - htmd-data >=0.0.20
    - anaconda-client
    - nglview
    - vina
    - psfgen
    - htmdbabel
    - pandas
    - pint
    - htmd-pdb2pqr >=2.1.2a7
    - spyder
    - psi4
    - htmdbabel
    - acemd
    - match
    - ambermini
    
test:
  commands:
    - htmd --help
    - ls package/htmd/parameterization/share/bin
about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
