about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt

package:
  name: htmd
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

  script_env:
   - OSNAME

  entry_points:
    - htmdnb    = htmdx.cli:main_htmd_notebook
    - htmd      = htmdx.cli:main_htmd
    - htmd_register   = htmdx.cli:main_do_nothing
    - parameterize = htmd.parameterization.cli:main_parameterize
    # - sample    = htmd.parameterization.sample:sample_main # TODO: Re-add when sample is refactored
    - activate_license  = htmdx.cli:main_activate

requirements:
  build:
    - python 
    - requests
    

  run:
    - python 
    - htmd-deps {{ environ.get('BUILD_VERSION') }}

