package:
  name: htmd
  version: "0.1.40"

source:
   path: ../..

build:
  entry_points:
    - htmdnb    = htmdx.cli:main_htmd_notebook
    - htmd      = htmdx.cli:main_htmd

requirements:
  build:
    - python >=3.4
    - requests
    

  run:
    - python >=3.4
    - pyemma >=2.0.2
    - natsort
    - joblib
    - requests
    - scikit-learn
    - ipython
    - jupyter_console
    - propka
    - notebook
    - ipywidgets
    - ipyparallel
    - htmd-data >=0.0.20
    - anaconda-client
    - nglview
    - vina
    
test:
  commands:
    - htmd --help
about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENSE.txt
