package:
  name: {{ environ.get('PACKAGE_NAME' ) }}
  version: {{ environ.get('BUILD_VERSION') }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  script_env:
   - TYPE
   - FC
   - CC
   - CROSS_COMPILE
   - STATIC
   - CPURE
   - OSNAME
   - TYPE

  entry_points:
    - htmdnb    = htmdx.cli:main_htmd_notebook
    - htmd      = htmdx.cli:main_htmd
    - parameterize    = htmd.parameterization.cli:main_parameterize
    - newparameterize = htmd.newparameterization.cli:main_parameterize
    - sample    = htmd.parameterization.sample:sample_main
    - activate_license  = htmdx.cli:main_activate

requirements:
  build:
    - python 
    - requests
    

  run:
    - python 
    - pyemma >=2.1
    - natsort
    - joblib
    - requests
    - scikit-learn
    - ipython
    - jupyter_console
    - propka >=3.1.6
    - notebook
    - ipywidgets
    - ipyparallel
    - htmd-data >=0.0.20
    - anaconda-client
    - nglview
    - vina
    - psfgen
    - pandas
    - pint
    - htmd-pdb2pqr >=2.1.2a7
    - spyder
    - psi4 <=2.0.0
    - acemd
    - match
    - ambermini 15.0.4
    - matplotlib
    - babel

# Remove this test which is now failing on Travis' OS X with Qt4 dylib error    
# No one uses this console entry point anyhow
#test:
#  commands:
#    - htmd --help

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
