package:
  name: htmd
  version: BUILD_VERSION_PLACEHOLDER

source:
   path: ../..

build:
  script_env:
   - OSNAME

  entry_points:
    - htmd_register   = htmd.license:htmd_register

requirements:
  build:
    - python 
    - requests
    - versioneer==0.28
    
  run:
DEPENDENCY_PLACEHOLDER

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
