name: Build docs

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.12"

      - name: Install docs deps
        run: uv sync --group docs

      - name: Build HTML
        run: cd doc && uv run make html

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_DOCS }}
          service_account: ${{ secrets.GCP_DOC_SERVICE_ACCOUNT }}

      - name: Sync HTML to GCP docs bucket
        run: |
          gcloud storage rsync doc/build/html gs://software-acellera-final/htmd \
            --recursive \
            --delete-unmatched-destination-objects
