name: Build docs

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  makedocs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: acellera,conda-forge,defaults

      - name: Install conda deps
        run: |
          mamba install -y -q --file package/htmd-deps/DEPENDENCIES nbconvert sphinx python=${{ matrix.python-version }} -c acellera -c conda-forge

      - name: Generate rst docs
        run: |
          cd doc; make rst

      - name: Publish to documentation server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: doc/source/
          remote_path: /home/docs/rst_docs/htmd/
          remote_host: ${{ secrets.DOCS_SSH_HOST }}
          remote_user: ${{ secrets.DOCS_SSH_USER }}
          remote_key: ${{ secrets.DOCS_SSH_KEY }}
