name: Test code

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name:
      run: |
        conda install --file package/htmd-deps/DEPENDENCIES -y -c acellera -c conda-forge  # Installing dependencies for tests

    - name: Install pip dependencies
      run: |
        pip install flake8 pytest coverage codecov
        pip install .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test
      run: |
        export HTMD_NONINTERACTIVE=1
        coverage run -m pytest --verbose --durations=10 ./htmd/
