#!/bin/bash
source ../routines

if [ "$1" == "--prepare" ]; then
	CHECK $BIN_GEN_ESP mol-opt.xyz $NetCharge  --prepare
elif [ "$1" == "--complete" ];then
	CHECK $BIN_GEN_ESP mol-opt.xyz $NetCharge  --complete
	CHECK $BIN_CHECK_B0_THETA0 
else
	CHECK $BIN_GEN_ESP mol-opt.xyz $NetCharge  --prepare
	CHECK $BIN_RUN_QM_JOBS
	CHECK $BIN_GEN_ESP mol-opt.xyz $NetCharge  --complete
	CHECK $BIN_CHECK_B0_THETA0 
fi

ln -s qm/mol-cgrid.out .
exit 0
