#!/bin/bash
source ../routines

#  cp ../150-fit_water/* .
#  cp ../240-1d-fitting/soft-dih-list.txt .
#  cp ../240-1d-fitting/saved-para.dat .
#  cp para-check.dat para-opt-start.dat

CHECK $BIN_FITCHARGE_AGAIN fit-mol.conf
CHECK $BIN_UPDATE_XPSF    


exit 0
