#!/bin/bash
source ../routines


CHECK $BIN_1D_FITTING

rm -Rf saved-para.dat
touch saved-para.dat

IdxTor=1
while [ -e torsion-para-${IdxTor}.dat ]; do
  head -n 1 torsion-para-${IdxTor}.dat >> saved-para.dat
  let IdxTor=IdxTor+1
done

exit 0
